# Generated by Django 3.2 on 2021-05-04 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='Descrição',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Preço',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='Quantia',
        ),
    ]
